---
title: "Immigration Attitudes"
format: html
editor: visual
---


##Question

What is the average causal effect of hearing Spanish on attitudes toward immigration among students in this class? 

Units? -> students 

Treatments? -> exposed to Spanish speaker vs no exposure

Outcomes? -> the attitude towards immigration 

covariants -> race, gender

Preceptor Table -> students, Outcomes (attitude if treated & attitude if control), causal effect (treatment - control)



Valitidy: the consistency, or lack there of, in the columns of our dataset and the corresponding columns in our Preceptor Table. In order to consider the two datasets to be drawn from the same population, the columns from one must be have a valid correspondence with the columns in the other. Validity, if true (or at least reasonable), allows us to construct the Population Table.






```{r}
library(tidyverse)
library(primer.data)



trains |> select(add_end, treatment)
  summarise(avg = mean(att_end), .by = treatment) |>
    mutate(ATE = )
    

#summary(trains)
```
